tests:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.spec.*'

ci:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**/**'

'frontend:store':
- changed-files:
  - any-glob-to-any-file:
    - 'frontend/store/**/*.ts'

'frontend:plugins':
- changed-files:
  - any-glob-to-any-file:
    - 'frontend/plugins/**/*.ts'

vue:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.vue'

packaging:
- changed-files:
  - any-glob-to-any-file:
    - 'packaging/**/**'

ui:
- changed-files:
  - any-glob-to-any-file:
    - 'frontend/components/**/*.vue'
    - 'frontend/layouts/**/*.vue'
    - 'frontend/pages/**/*.vue'
