# Build final image
FROM node:12-alpine

WORKDIR /app

COPY .docker/package.json .docker/nuxt.config.js ./

# Copy client files from the build image
COPY dist/ ./.nuxt/

# Install runtime dependencies
RUN yarn install --production

EXPOSE 80

CMD [ "yarn", "start" ]
