packages:
  - packaging/tauri
  - packages/*

saveExact: true
engineStrict: true
ignoreDepScripts: true
blockExoticSubdeps: true
packageImportMethod: hardlink
lockfileIncludeTarballUrl: true
linkWorkspacePackages: deep
injectWorkspacePackages: true
shamefullyHoist: true
fetchRetries: 15

catalogs:
  runtime:
    vue: 3.5.31
    '@vue/shared': 3.5.31
    '@vueuse/core': 14.2.1
    comlink: 4.4.2
    date-fns: 4.1.0
    i18next: 26.0.3
    i18next-vue: 5.4.0
    vuetify: 3.11.3
  development:
    find-up-simple: 1.0.1
    unplugin-vue-components: 32.0.0
