packages:
  - packaging/tauri
  - packages/*
allowBuilds:
  '@skirtle/vue-vnode-utils': false
  esbuild: true
  unrs-resolver: true

catalogs:
  development:
    find-up-simple: 1.0.1
    unocss: 66.6.8
    unplugin-vue-components: 32.0.0
    vite: 8.0.10
  runtime:
    '@vue/shared': 3.5.33
    '@vueuse/core': 14.2.1
    comlink: 4.4.2
    date-fns: 4.1.0
    i18next: 26.0.8
    i18next-vue: 5.4.0
    vue: 3.5.33
    vuetify: 3.11.3

dedupePeers: true
engineStrict: true
fetchRetries: 15
injectWorkspacePackages: true
linkWorkspacePackages: deep
lockfileIncludeTarballUrl: true
packageImportMethod: hardlink
saveExact: true
shamefullyHoist: true
strictDepBuilds: false
