name: Bug Report
description: You have noticed a general issue or regression, and would like to report it
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Please note that contributor time is limited, and we might not get back to you immediately.
        Also make sure to check if [an existing issue] matches yours.
  - type: textarea
    attributes:
      label: Description of the bug
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Explain how a maintainer can reliably reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: If relevant, provide *browser* logs indicating an error.
      render: text
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: dropdown
    attributes:
      label: Platform
      options:
        - Linux
        - Windows
        - macOS
        - Android
        - iOS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browser
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Other (Please specify in the "additional context" section)
    validations:
      required: true
  - type: input
    attributes:
      label: Jellyfin server version
      placeholder: 10.7.6
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: If necessary, provide any further context or information.
      render: text
