/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/artist/[itemId]': RouteRecordInfo<
      '/artist/[itemId]',
      '/artist/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/genre/[itemId]': RouteRecordInfo<
      '/genre/[itemId]',
      '/genre/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/item/[itemId]': RouteRecordInfo<
      '/item/[itemId]',
      '/item/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/library/[itemId]': RouteRecordInfo<
      '/library/[itemId]',
      '/library/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/metadata': RouteRecordInfo<
      '/metadata',
      '/metadata',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/musicalbum/[itemId]': RouteRecordInfo<
      '/musicalbum/[itemId]',
      '/musicalbum/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/person/[itemId]': RouteRecordInfo<
      '/person/[itemId]',
      '/person/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/playback/music': RouteRecordInfo<
      '/playback/music',
      '/playback/music',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/playback/video': RouteRecordInfo<
      '/playback/video',
      '/playback/video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/series/[itemId]': RouteRecordInfo<
      '/series/[itemId]',
      '/series/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/server/add': RouteRecordInfo<
      '/server/add',
      '/server/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/login': RouteRecordInfo<
      '/server/login',
      '/server/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/select': RouteRecordInfo<
      '/server/select',
      '/server/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/apikeys': RouteRecordInfo<
      '/settings/apikeys',
      '/settings/apikeys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/devices': RouteRecordInfo<
      '/settings/devices',
      '/settings/devices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/logs-and-activity': RouteRecordInfo<
      '/settings/logs-and-activity',
      '/settings/logs-and-activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/server': RouteRecordInfo<
      '/settings/server',
      '/settings/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/subtitles': RouteRecordInfo<
      '/settings/subtitles',
      '/settings/subtitles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/users/': RouteRecordInfo<
      '/settings/users/',
      '/settings/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/users/[id]': RouteRecordInfo<
      '/settings/users/[id]',
      '/settings/users/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/users/new': RouteRecordInfo<
      '/settings/users/new',
      '/settings/users/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/wizard': RouteRecordInfo<
      '/wizard',
      '/wizard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/artist/[itemId].vue': {
      routes:
        | '/artist/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/genre/[itemId].vue': {
      routes:
        | '/genre/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/item/[itemId].vue': {
      routes:
        | '/item/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/library/[itemId].vue': {
      routes:
        | '/library/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/metadata.vue': {
      routes:
        | '/metadata'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/musicalbum/[itemId].vue': {
      routes:
        | '/musicalbum/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/person/[itemId].vue': {
      routes:
        | '/person/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/playback/music.vue': {
      routes:
        | '/playback/music'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/playback/video.vue': {
      routes:
        | '/playback/video'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/series/[itemId].vue': {
      routes:
        | '/series/[itemId]'
      views:
        | never
      pathParamNames:
        | 'itemId'
    }
    'src/pages/server/add.vue': {
      routes:
        | '/server/add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/login.vue': {
      routes:
        | '/server/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server/select.vue': {
      routes:
        | '/server/select'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/apikeys.vue': {
      routes:
        | '/settings/apikeys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/devices.vue': {
      routes:
        | '/settings/devices'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/logs-and-activity.vue': {
      routes:
        | '/settings/logs-and-activity'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/server.vue': {
      routes:
        | '/settings/server'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/subtitles.vue': {
      routes:
        | '/settings/subtitles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/users/index.vue': {
      routes:
        | '/settings/users/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/users/[id].vue': {
      routes:
        | '/settings/users/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/settings/users/new.vue': {
      routes:
        | '/settings/users/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/wizard.vue': {
      routes:
        | '/wizard'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
