/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NameIdPair } from './name-id-pair';
import { NameValuePair } from './name-value-pair';
import { TunerChannelMapping } from './tuner-channel-mapping';

/**
 * Channel mapping options dto.
 * @export
 * @interface ChannelMappingOptionsDto
 */
export interface ChannelMappingOptionsDto {
    /**
     * Gets or sets list of tuner channels.
     * @type {Array<TunerChannelMapping>}
     * @memberof ChannelMappingOptionsDto
     */
    TunerChannels?: Array<TunerChannelMapping> | null;
    /**
     * Gets or sets list of provider channels.
     * @type {Array<NameIdPair>}
     * @memberof ChannelMappingOptionsDto
     */
    ProviderChannels?: Array<NameIdPair> | null;
    /**
     * Gets or sets list of mappings.
     * @type {Array<NameValuePair>}
     * @memberof ChannelMappingOptionsDto
     */
    Mappings?: Array<NameValuePair> | null;
    /**
     * Gets or sets provider name.
     * @type {string}
     * @memberof ChannelMappingOptionsDto
     */
    ProviderName?: string | null;
}


