/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DeviceProfile } from './device-profile';
import { GeneralCommandType } from './general-command-type';

/**
 * Client capabilities dto.
 * @export
 * @interface ClientCapabilitiesDto
 */
export interface ClientCapabilitiesDto {
    /**
     * Gets or sets the list of playable media types.
     * @type {Array<string>}
     * @memberof ClientCapabilitiesDto
     */
    PlayableMediaTypes?: Array<string> | null;
    /**
     * Gets or sets the list of supported commands.
     * @type {Array<GeneralCommandType>}
     * @memberof ClientCapabilitiesDto
     */
    SupportedCommands?: Array<GeneralCommandType> | null;
    /**
     * Gets or sets a value indicating whether session supports media control.
     * @type {boolean}
     * @memberof ClientCapabilitiesDto
     */
    SupportsMediaControl?: boolean;
    /**
     * Gets or sets a value indicating whether session supports content uploading.
     * @type {boolean}
     * @memberof ClientCapabilitiesDto
     */
    SupportsContentUploading?: boolean;
    /**
     * Gets or sets the message callback url.
     * @type {string}
     * @memberof ClientCapabilitiesDto
     */
    MessageCallbackUrl?: string | null;
    /**
     * Gets or sets a value indicating whether session supports a persistent identifier.
     * @type {boolean}
     * @memberof ClientCapabilitiesDto
     */
    SupportsPersistentIdentifier?: boolean;
    /**
     * Gets or sets a value indicating whether session supports sync.
     * @type {boolean}
     * @memberof ClientCapabilitiesDto
     */
    SupportsSync?: boolean;
    /**
     * 
     * @type {DeviceProfile}
     * @memberof ClientCapabilitiesDto
     */
    DeviceProfile?: DeviceProfile;
    /**
     * Gets or sets the app store url.
     * @type {string}
     * @memberof ClientCapabilitiesDto
     */
    AppStoreUrl?: string | null;
    /**
     * Gets or sets the icon url.
     * @type {string}
     * @memberof ClientCapabilitiesDto
     */
    IconUrl?: string | null;
}


