/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IScheduledTask } from './ischeduled-task';
import { TaskResult } from './task-result';
import { TaskState } from './task-state';
import { TaskTriggerInfo } from './task-trigger-info';

/**
 * Interface IScheduledTaskWorker.
 * @export
 * @interface IScheduledTaskWorker
 */
export interface IScheduledTaskWorker {
    /**
     * 
     * @type {IScheduledTask}
     * @memberof IScheduledTaskWorker
     */
    ScheduledTask?: IScheduledTask;
    /**
     * 
     * @type {TaskResult}
     * @memberof IScheduledTaskWorker
     */
    LastExecutionResult?: TaskResult;
    /**
     * Gets the name.
     * @type {string}
     * @memberof IScheduledTaskWorker
     */
    Name?: string | null;
    /**
     * Gets the description.
     * @type {string}
     * @memberof IScheduledTaskWorker
     */
    Description?: string | null;
    /**
     * Gets the category.
     * @type {string}
     * @memberof IScheduledTaskWorker
     */
    Category?: string | null;
    /**
     * 
     * @type {TaskState}
     * @memberof IScheduledTaskWorker
     */
    State?: TaskState;
    /**
     * Gets the current progress.
     * @type {number}
     * @memberof IScheduledTaskWorker
     */
    CurrentProgress?: number | null;
    /**
     * Gets the triggers that define when the task will run.
     * @type {Array<TaskTriggerInfo>}
     * @memberof IScheduledTaskWorker
     */
    Triggers?: Array<TaskTriggerInfo> | null;
    /**
     * Gets the unique id.
     * @type {string}
     * @memberof IScheduledTaskWorker
     */
    Id?: string | null;
}


