/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LogFile
 */
export interface LogFile {
    /**
     * Gets or sets the date created.
     * @type {string}
     * @memberof LogFile
     */
    DateCreated?: string;
    /**
     * Gets or sets the date modified.
     * @type {string}
     * @memberof LogFile
     */
    DateModified?: string;
    /**
     * Gets or sets the size.
     * @type {number}
     * @memberof LogFile
     */
    Size?: number;
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof LogFile
     */
    Name?: string | null;
}


