/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PathSubstitution
 */
export interface PathSubstitution {
    /**
     * 
     * @type {string}
     * @memberof PathSubstitution
     */
    From?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PathSubstitution
     */
    To?: string | null;
}


