/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Class RepositoryInfo.
 * @export
 * @interface RepositoryInfo
 */
export interface RepositoryInfo {
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof RepositoryInfo
     */
    Name?: string | null;
    /**
     * Gets or sets the URL.
     * @type {string}
     * @memberof RepositoryInfo
     */
    Url?: string | null;
    /**
     * Gets or sets a value indicating whether the repository is enabled.
     * @type {boolean}
     * @memberof RepositoryInfo
     */
    Enabled?: boolean;
}


