/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Version
 */
export interface Version {
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    Major?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    Minor?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    Build?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    Revision?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    MajorRevision?: number;
    /**
     * 
     * @type {number}
     * @memberof Version
     */
    MinorRevision?: number;
}


