/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LibraryOptions } from './library-options';

/**
 * Used to hold information about a user\'s list of configured virtual folders.
 * @export
 * @interface VirtualFolderInfo
 */
export interface VirtualFolderInfo {
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    Name?: string | null;
    /**
     * Gets or sets the locations.
     * @type {Array<string>}
     * @memberof VirtualFolderInfo
     */
    Locations?: Array<string> | null;
    /**
     * Gets or sets the type of the collection.
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    CollectionType?: string | null;
    /**
     * 
     * @type {LibraryOptions}
     * @memberof VirtualFolderInfo
     */
    LibraryOptions?: LibraryOptions;
    /**
     * Gets or sets the item identifier.
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    ItemId?: string | null;
    /**
     * Gets or sets the primary image item identifier.
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    PrimaryImageItemId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VirtualFolderInfo
     */
    RefreshProgress?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VirtualFolderInfo
     */
    RefreshStatus?: string | null;
}


