/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Defines the MediaBrowser.Model.Dlna.XmlAttribute.
 * @export
 * @interface XmlAttribute
 */
export interface XmlAttribute {
    /**
     * Gets or sets the name of the attribute.
     * @type {string}
     * @memberof XmlAttribute
     */
    Name?: string | null;
    /**
     * Gets or sets the value of the attribute.
     * @type {string}
     * @memberof XmlAttribute
     */
    Value?: string | null;
}


