name: Quality checks 👌🧪

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
  workflow_dispatch:

jobs:
  dependency-review:
    name: Vulnerable dependencies 🔎
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit }}
          show-progress: false

      - name: Scan
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          base-ref: ${{ github.event.pull_request.base.sha || 'master' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}

  quality:
    name: Run ${{ matrix.command }} 🕵️‍♂️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint
          - test
          - check:types
          # Checks for dependency cycles in the bundle and in the monorepo setup
          - analyze:cycles
          - 'pnpm i --lockfile-only --config.disallow-workspace-cycles=true'

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit }}
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          check-latest: true

      - name: Install dependencies 📦
        run: corepack pnpm i --frozen-lockfile

      - name: Run ${{ matrix.command }} ⚙️
        run: corepack pnpm ${{ matrix.command }}

  commits_checks:
    name: Commit linting 💬✅
    runs-on: ubuntu-slim

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit }}
          show-progress: false

      - name: Check if all commits comply with the specification
        uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1

      - name: Check for merge commits
        run: |
          git log --merges --oneline | grep -q "^" && exit 1 || exit 0

