# This dockerfile is just for CI purposes. It needs the client
# built in the host in order to be created and deployed

FROM nginx:alpine
COPY dist/ /usr/share/nginx/html/
COPY .docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY .docker/mime.types /etc/nginx/mime.types
